# Generated by Django 2.2.19 on 2021-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephones', '0002_auto_20211125_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='--пусто--', max_length=20),
        ),
    ]
